backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "latest-news"
    label: "Latest News"
    folder: "src/pages/latest-news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "news-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Call To Action,
              name: calltoactions,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: "Link Type",
                    name: "linkType",
                    widget: "select",
                    options: ["internal", "external"],
                  },
                  {
                    label: "Link URL",
                    name: "linkURL",
                    widget: "string",
                    hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                  },
                ],
            }
      - file: "src/pages/history/index.md"
        label: "History"
        name: "history"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "history-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/how-to-help/index.md"
        label: "How To Help"
        name: "how-to-help"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "how-to-help-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }